export const ITEM_SELECTED = 'ITEM_SELECTED';
export const DELETE_ORDERED_ITEM = 'DELETE_ORDERED_ITEM';
export const CREATE_ORDER = 'CREATE_ORDER';
export const CLEAR_ALL_ORDERED_ITEMS = 'CLEAR_ALL_ORDERED_ITEMS';
