export const ITEM_SELECTED = 'ITEM_SELECTED';
export const DELETE_ORDERED_ITEM = 'DELETE_ORDERED_ITEM';
export const CREATE_ORDER = 'CREATE_ORDER';
export const CLEAR_ALL_ORDERED_ITEMS = 'CLEAR_ALL_ORDERED_ITEMS';
export const EDIT_ORDERED_ITEM = 'EDIT_ORDERED_ITEM';
export const SET_CURRENT_TABLE_NO = 'SET_CURRENT_TABLE_NO';
export const PAYMENT_DONE = 'PAYMENT_DONE';
